[package]
name = "temproject"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
serde_yaml = "0.9.34"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
